---
title: "Article 1 : Old cells, new tricks : important clue to AML diagnosis and treatment discovered"
author:
  - name: François L'Hoir
date: 10-20-2019
categories:
  - leukemia
preview: image/cells.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Source
Science Daily : https://www.sciencedaily.com/releases/2019/08/190801142529.htm 

## Vocabulary 

| Words from text                | Synonym/ explanation in English                                |
| ------------------------------ | -------------------------------------------------------------- |
| Acute                          | Opposite of chronic                                            |
| To crowd                       | To invade                                                      |
| Bone marrow                    | Tissue inside the bone                                         |
| Poor outcomes                  | Bad results                                                    |
| Stem cells                     | Immatures cells that can differenciate into several cell types |
| Hence                          | Consequently                                                   |
| Aimed                          | Targeted                                                       |
| Irrespective of maturate state | No matter the maturate state                                   |
| Counterpart                    | Correspondent, analogue                                        |

## Analysis table 

|                               |                                                                                                                                                                                                                                                                                                                                                                                                                              |
| ----------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers                   | Professor Ross Dickins (from Australian Center for Blood Disease). Researchers from Australia’s Monash University. Researchers from Walter and Eliza Hall Institute of Medical Research                                                                                                                                                                                                                                      |
| Published in ?                | August 1, 2019                                                                                                                                                                                                                                                                                                                                                                                                               |
| General topic ?               | The article presents a new discovery that explains the difficulty of treating acute myeloid leukemia. This disease is one of the most common and aggressive leukemia.                                                                                                                                                                                                                                                        |
| Procedure/what was examined ? | They used genetically engineered mouse models and human leukemic cells.                                                                                                                                                                                                                                                                                                                                                      |
| Conclusions/discovery ?       | Acute myeloid leukemia is  a proliferation of immature leukemic cells (leukaemia stem cells). When these cells mature they lose their cancerous properties. Researchers have shown that matures leukemic cells can become immature again then they contribute to development of leukemia and resistance to treatment. This is an important discovery because the main therapeutic strategy is to target only immature cells. |
| Remaining questions ?         | Now, new therapeutic strategies must be developed that target both mature and immature cells at the same time.                                                                                                                                                                                                                                                                                                               |
