---
title: "My English Activity Log M.E.A.L"
author:
  - name: François L'Hoir
    url: {}
date: 11-11-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Nov. 9th : I read scientific articles on the phylogeny of chaetognaths for the course of molecular phylogeny. It's a bit dificult to understand but it's very interesting.

Nov 23th : I watched an episode of "The Good Place" in English with English subtitles. I usually watch series in English subtitled in French but it was the first time I watched with English subtitles.

Nov 27th : I began to read "The Handmaid's Tale" in English. I have already seen the series (in English with French subtitles) and I liked it but I heard that there was a lot of difference with the book.

Feb 16th : Last week I finished watching the series "the good place" in English with English subtitles. I also watched 2 episodes of "the witcher" in English with French subtitles. I keep reading "the handmaid's tale" but it's not easy and I read slowly.
